# SwiftLint Configuration
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - BoilerplateApp
  - BoilerplateAppTests

# Paths to exclude during linting
excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - BoilerplateApp/Resources

# Enabled rules (on top of defaults)
opt_in_rules:
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Can be annoying in multiline strings
  - todo  # Allow TODO comments
  - vertical_whitespace_opening_braces  # Too strict for readability
  - attributes  # Too strict for SwiftUI property wrappers
  - sorted_imports  # Minor style preference
  - trailing_closure  # Can reduce clarity in some cases

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_name:
  min_length: 2
  max_length:
    warning: 50
    error: 60

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - ok

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

cyclomatic_complexity:
  warning: 15
  error: 25

large_tuple:
  warning: 3
  error: 4

closure_body_length:
  warning: 40
  error: 60

force_cast: warning
force_try: warning
force_unwrapping: warning
implicitly_unwrapped_optional: warning

# Custom rules
custom_rules:
  no_print:
    included: ".*\\.swift"
    excluded: ".*Tests\\.swift"
    name: "No print statements"
    regex: "\\bprint\\s*\\("
    message: "Use Log instead of print"
    severity: warning

  mark_comment_spacing:
    included: ".*\\.swift"
    name: "MARK comment spacing"
    regex: "//\\s*MARK:[^ ]"
    message: "MARK comments should have a space after the colon"
    severity: warning

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"
