name: BoilerplateApp
options:
  bundleIdPrefix: com.yourcompany
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

configFiles:
  Debug: BoilerplateApp/Configuration/Debug.xcconfig
  Release: BoilerplateApp/Configuration/Production.xcconfig

settings:
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""

targets:
  BoilerplateApp:
    type: application
    platform: iOS
    sources:
      - path: BoilerplateApp
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_NAME: BoilerplateApp
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.boilerplateapp
        INFOPLIST_FILE: BoilerplateApp/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: true
    entitlements:
      path: BoilerplateApp/BoilerplateApp.entitlements
      properties:
        aps-environment: development
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.yourcompany.boilerplateapp
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        basedOnDependencyAnalysis: false

  BoilerplateAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: BoilerplateAppTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: BoilerplateApp
    settings:
      base:
        PRODUCT_NAME: BoilerplateAppTests
        PRODUCT_MODULE_NAME: BoilerplateAppTests
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.boilerplateapp.tests
        INFOPLIST_FILE: BoilerplateAppTests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BoilerplateApp.app/BoilerplateApp"
        BUNDLE_LOADER: "$(TEST_HOST)"

  BoilerplateAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: BoilerplateAppUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: BoilerplateApp
    settings:
      base:
        PRODUCT_NAME: BoilerplateAppUITests
        PRODUCT_MODULE_NAME: BoilerplateAppUITests
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.boilerplateapp.uitests
        INFOPLIST_FILE: BoilerplateAppUITests/Info.plist
        TEST_TARGET_NAME: BoilerplateApp

schemes:
  BoilerplateApp:
    build:
      targets:
        BoilerplateApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - BoilerplateAppTests
        - BoilerplateAppUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
