name: KensIOSApp
options:
  bundleIdPrefix: com.kenkai
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

configFiles:
  Debug: KensIOSApp/Configuration/Debug.xcconfig
  Release: KensIOSApp/Configuration/Production.xcconfig

settings:
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: ""

targets:
  KensIOSApp:
    type: application
    platform: iOS
    sources:
      - path: KensIOSApp
        excludes:
          - "**/.DS_Store"
          - "Configuration"
    settings:
      base:
        PRODUCT_NAME: KensIOSApp
        PRODUCT_BUNDLE_IDENTIFIER: com.kenkai.kensiosapp
        INFOPLIST_FILE: KensIOSApp/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
        SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: true
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    entitlements:
      path: KensIOSApp/KensIOSApp.entitlements
      properties:
        aps-environment: development
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.kenkai.kensiosapp
    preBuildScripts:
      - name: SwiftLint
        script: |
          # Check common installation paths for SwiftLint
          if [ -f /opt/homebrew/bin/swiftlint ]; then
            SWIFTLINT=/opt/homebrew/bin/swiftlint
          elif [ -f /usr/local/bin/swiftlint ]; then
            SWIFTLINT=/usr/local/bin/swiftlint
          elif which swiftlint > /dev/null; then
            SWIFTLINT=swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
            exit 0
          fi
          cd "$SRCROOT"
          "$SWIFTLINT" lint KensIOSApp
        basedOnDependencyAnalysis: false

  KensIOSAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: KensIOSAppTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KensIOSApp
    settings:
      base:
        PRODUCT_NAME: KensIOSAppTests
        PRODUCT_MODULE_NAME: KensIOSAppTests
        PRODUCT_BUNDLE_IDENTIFIER: com.kenkai.kensiosapp.tests
        INFOPLIST_FILE: KensIOSAppTests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/KensIOSApp.app/KensIOSApp"
        BUNDLE_LOADER: "$(TEST_HOST)"

  KensIOSAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: KensIOSAppUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: KensIOSApp
    settings:
      base:
        PRODUCT_NAME: KensIOSAppUITests
        PRODUCT_MODULE_NAME: KensIOSAppUITests
        PRODUCT_BUNDLE_IDENTIFIER: com.kenkai.kensiosapp.uitests
        INFOPLIST_FILE: KensIOSAppUITests/Info.plist
        TEST_TARGET_NAME: KensIOSApp

schemes:
  KensIOSApp:
    build:
      targets:
        KensIOSApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - KensIOSAppTests
        - KensIOSAppUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
